# Generated by Django 4.1.5 on 2023-01-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_blogtitle_alter_blog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='blogContent',
        ),
    ]
